version: "2"
checks:
    argument-count:
        config:
            threshold: 6
    method-complexity:
        config:
            threshold: 15
exclude_patterns:
    - ".nyc_output/"
    - node_modules/
    - coverage/
    - .vscode/
    - single_repo/
    - test/
    - templates/
    - ".*"
    - "./**.json"
    - "./*.js"
    - "**/*.d.ts"
