branches:
  except:
    - /^v\d+\.\d+\.\d+$/
language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g semantic-release
  - npm install -g codeclimate-test-reporter
install:
  - npm i .
script:
  - npm run cover
after_success:
  - npm run export
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run semantic-release
